server:
  port: 0
spring:
  application:
    name: customerservice
  datasource:
    url: jdbc:postgresql://localhost:5431/customers
    driver-class-name: org.postgresql.Driver
    username: oscirt
    password: 12345
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    user: oscirt
    password: 12345
    default-schema: customers
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
