server:
  port: 0
spring:
  application:
    name: deposits
  datasource:
    url: jdbc:postgresql://localhost:5432/deposits
    driver-class-name: org.postgresql.Driver
    username: tricso
    password: 54321
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    user: tricso
    password: 54321
    default-schema: deposits
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka